cc_library(
    name = 'global_buff',
    srcs = 'global_buff.cc',
)

cc_library(
    name = 'file_reader',
    srcs = 'file_reader.cc',
)


cc_library(
    name = 'run_flags',
    srcs = 'run_flags.cc',
)

