
cc_binary(
	name = 'zone_svr',
	srcs = [
		'main.cc',

		'system/world.cc',
	],

	incs = [
		'../../Zone/src/framework',
		'../../Zone/src/system',
		'../../Zone/src/model',

	],

	deps = [
		
	],
	defs = [
	],
)
