cc_library(
	name = 'network',
	srcs = [
		'socket.cc',
		'tcp_socket.cc',
		'socket_manager.cc',
		'epoll_socket_manager.cc',
	],

	incs = [        
		"../../common/platform",
	],

	deps = [
        "//common/platform:platform",
	]
)
